name: 'Claude Code Review Action'
description: 'Automated code review using Anthropic Claude AI for GitHub pull requests'
author: 'pylesoft'

inputs:
  claude_code_oauth_token:
    description: 'OAuth token for Claude Code API authentication'
    required: true
  mode:
    description: 'Review mode (experimental-review or review)'
    required: false
    default: 'experimental-review'
  timeout_minutes:
    description: 'Timeout in minutes for the review process'
    required: false
    default: '30'
  custom_instructions:
    description: 'Custom instructions for Claude to follow during review'
    required: false
    default: |
      Focus on:
      - Code quality and maintainability
      - Security vulnerabilities
      - Performance issues
      - Best practices and design patterns
      - Test coverage gaps
      
      Be constructive and provide specific suggestions for improvements.
      Use GitHub's suggestion format when proposing code changes.

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Claude Code Review
      uses: anthropics/claude-code-action@beta
      with:
        mode: ${{ inputs.mode }}
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        timeout_minutes: ${{ inputs.timeout_minutes }}
        custom_instructions: ${{ inputs.custom_instructions }}

branding:
  icon: 'eye'
  color: 'purple'